# Generated by Django 2.2.6 on 2019-10-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la cancha. Ejemplo: La Diego Armando', max_length=250, verbose_name='Nombre de la cancha')),
                ('cod_interno', models.CharField(help_text='Codigo interno de la cancha. Ejemplo: ful-AF321', max_length=20, verbose_name='Codigo Interno')),
                ('tiene_vestuario', models.BooleanField(default=False, help_text='Marque esta opción si la cancha tiene vestuario', verbose_name='¿Tiene vestuario?')),
                ('tiene_iluminacion', models.BooleanField(default=False, help_text='Marque esta opción si la cancha tiene iluminación', verbose_name='¿Tiene iluminación?')),
                ('tiene_cesped_sintetico', models.BooleanField(default=False, help_text='Marque esta opción si la cancha posee césped sintético', verbose_name='¿Tiene césped sintético?')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cancha', models.CharField(help_text='Ingrese el tipo de cancha. Ejemplo: Cancha 11, Cancha 7, etc.', max_length=50, verbose_name='Tipo de cancha')),
            ],
            options={
                'verbose_name': 'Tipo de Cancha',
                'verbose_name_plural': 'Tipos de Cancha',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(help_text='Ingrese el nombre del cliente', max_length=250, verbose_name='Nombre del cliente')),
                ('fecha_turno', models.DateTimeField(help_text='Seleccione la fecha y la hora en la que se usará la cancha', verbose_name='Fecha del turno')),
                ('fecha_reserva', models.DateField(auto_now_add=True, verbose_name='Fecha de la reserva')),
                ('cancha', models.ForeignKey(help_text='Seleccione la cancha que desea reservar', on_delete=django.db.models.deletion.CASCADE, to='reservas.Cancha', verbose_name='Cancha solicitada')),
                ('empleado', models.ForeignKey(help_text='Empleado que tomó la reserva', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Empleado de turno')),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo',
            field=models.ForeignKey(help_text='Seleccione el tipo de cancha', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.TipoCancha', verbose_name='Tipo de cancha'),
        ),
    ]
