# Generated by Django 2.2.6 on 2019-11-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20191101_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva', 'hora_turno'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
