# Generated by Django 2.2.6 on 2019-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20191103_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva', 'fecha_turno'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_turno',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_turno',
            field=models.DateTimeField(help_text='Seleccione la fecha y hora en la que se usará la cancha', verbose_name='Fecha del turno'),
        ),
    ]
