# Generated by Django 2.2.6 on 2019-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20191104_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva', 'fecha_turno', 'hora_turno'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_turno',
            field=models.TimeField(default='00:00:00', help_text='Ingrese la hora en la que se usará la cancha. (No se pueden transponer).', verbose_name='Hora del turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_turno',
            field=models.DateField(help_text='Seleccione la fecha en la que se usará la cancha', verbose_name='Fecha del turno'),
        ),
    ]
